apiVersion: v2
name: ark-demo
description: A Helm chart for dwmkerr's Ark demo models and agents
type: application
version: 0.1.7
appVersion: 0.1.7
annotations:
  ark.mckinsey.com/service: ark-demo
dependencies:
  - name: ai-developer-guide-mcp
    version: '>=0.1.0'
    repository: oci://ghcr.io/dwmkerr/charts
    condition: mcpServers.aiDeveloperGuide.enabled
  - name: shell-mcp
    version: '>=0.1.0'
    repository: oci://ghcr.io/dwmkerr/charts
    condition: mcpServers.shell.enabled
  - name: github-mcp
    version: '>=0.1.0'
    repository: oci://ghcr.io/dwmkerr/charts
    condition: mcpServers.github.enabled
